services:
  - type: web
    name: melanoma-detect
    runtime: docker
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: melanoma-detect
          property: host
      - key: GEMINI_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_OWNER_EMAIL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SMTP_LOGIN
        sync: false
